### ISSUE TITLE
feat: make hero section more responsive

### ISSUE THREAD

**Issue by jessej-samuel** [dscvitc/dscvitchennai#10]
Hi! Right now the hero section has lots of breaks `<br />` viz inconsistent while scaling.
![image](https://user-images.githubusercontent.com/72020411/194080021-0ea1e325-41b6-4134-b39e-bd18aa6d6e3b.png)
Can I work on making it more responsive for screens bigger than mobile? [cuz Idk how the design for mobile looks yet 😅]

**Comment by FidalMathew** [comment]
Sure go ahead! If you'd like to work on the responsiveness of smaller screens. You can create a separate PR for a Navbar. I don't think it would require any such designs. @jessej-samuel

**Comment by jessej-samuel** [comment]
Hey @FidalMathew, it seems @mr-vijaychauhan has already started working on refactoring the hero section code in #11. So, I'll wait till they finish to prevent writing redundant code.

**Comment by mr-vijaychauhan** [comment]
ok no problem

**Comment by jessej-samuel** [comment]
Hey, I've fixed this issue. Review the pr and lmk if any changes are required!

**Comment by jessej-samuel** [comment]
Fixed in #38
