### ISSUE TITLE
Hero Section and Vision Section using Pure Tailwind Css 

### ISSUE THREAD

**Issue by mr-vijaychauhan** [dscvitc/dscvitchennai#11]
I create this design with Pure Tailwind Css. I'm very close to this design.

- Home Section (Hero Section)
- Vision Section with Dynamic grid
- Title and Arrow with separate components

Can you assign me to work this design ?

![GDSC-Design](https://user-images.githubusercontent.com/63604585/194340793-f733a9b6-09cc-4f09-9c84-4679b19fcad2.png)

**Comment by FidalMathew** [comment]
@mr-vijaychauhan yes, please. Go ahead!

**Comment by mr-vijaychauhan** [comment]
ok

**Comment by FidalMathew** [comment]
![image](https://user-images.githubusercontent.com/84982038/194514162-bdb7b59b-4437-43ed-b170-129c5888f3a1.png)
Try to fit the content in lesser width as in the website design. @mr-vijaychauhan

**Comment by mr-vijaychauhan** [comment]
Ok I will try my best. can you add lable hacktoberfest ??

**Comment by FidalMathew** [comment]
There's no need of adding hacktoberfest label to issues. The GitHub repository has the hacktoberfest label. You don't need to worry about that :)
