### ISSUE TITLE
Contributors page is not functioning

### ISSUE THREAD

**Issue by EmmanuelAllanMJ** [dscvitc/dscvitchennai#119]
### Description

This should display the list of contributors of this repo

### Expected Behaviour

![image](https://github.com/dscvitc/dscvitchennai/assets/90669430/56f7ac7d-3566-4d1f-9110-72abae52841a)

![image](https://github.com/dscvitc/dscvitchennai/assets/90669430/a9bb0a00-1200-4156-8840-1a690a1798cf)

### What happened?

It seems the api folder is misplaced and is not configured properly. At the end we should get details in /api/contributors endpoint

### Version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Malay-dev** [comment]
Hey @EmmanuelAllanMJ, Can I work on this issue... Please assign it to me...

**Comment by Malay-dev** [comment]
Thank you @EmmanuelAllanMJ... It was a great pleasure working on this project... :blush:
