### ISSUE TITLE
feat: Come up with theme colors following official GDSC page

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#14]
We need some theme colours, which can then be included in the `talwind.config.js` 
Refer the official google or [GDSC](https://gdsc.community.dev/) websites for inspiration

**Comment by mohammadshaad** [comment]
I can work on this. I will search for the theme colour for the website.

**Comment by sn10-debug** [comment]
Can you please assign me this issue as @mohammadshaad has already got one pull request ? I will react out with the theme as soon as possible

**Comment by Arjun31415** [comment]
> Can you please assign me this issue as @mohammadshaad has already got one pull request ? I will react out with the theme as soon as possible

Would you like to work on the latest issue #22

**Comment by sn10-debug** [comment]
@Arjun31415 Is it possible if I get the theme colours first then it will be accepted?

**Comment by Arjun31415** [comment]
> @Arjun31415 Is it possible if I get the theme colours first then it will be accepted?

No I cannot do that, please request for the issue to be assigned and then I will

**Comment by Arjun31415** [comment]
If the current assignee is unable to complete for certain reasons then I will be re-assigning. Do not worry there will be more issues throughout October

**Comment by Arjun31415** [comment]
Resolved in #32
