### ISSUE TITLE
Multiple `img` tag in codebase

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#17]
There are multiple `img` tags present in the entire codebase. Especially the `Index.js` file. 
It is better to use `next/Image` as compared to `img`. 

- [x] Replace `img` tag with `next/Image` in `Index.js`
- [x] Replace `img` rtag with `next/Image` in `components/contributors/List.js`

**Comment by mohammadshaad** [comment]
I can do these changes. Kindly assign me this issue

**Comment by Arjun31415** [comment]
As an example please check out 
https://github.com/dscvitc/dscvitchennai/blob/27e8146139cdecd596f5d4d4a48681b3aac7fc0d/components/Navbar.js#L16

**Comment by Arjun31415** [comment]
> I can do these changes. Kindly assign me this issue

Assigned

**Comment by sn10-debug** [comment]
@Arjun31415 
#21 Code is successfully deployed

**Comment by mohammadshaad** [comment]
@Arjun31415 
#19 PR has been made please check

**Comment by Arjun31415** [comment]
closed by #19
