### ISSUE TITLE
feat: Add a carousel for the current core team.

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#22]
We need to add a carousel for the current core team on the home page. It can use dummy images for now, The names need to be listed and their designation
- [ ] Arjun Prashanth - Web Development Lead
- [ ] Aaron Ritesh- Data Science Lead
- [ ] Apoorva - Desgin Lead
- [ ] Fidal Mathew - Open Source Lead
- [ ] Harisha S - Overall GDSC Lead and Outreach Lead
- [ ] Manas Tiwari - Competitive Programming Lead
- [ ] Narayan - Blockchain Lead
- [ ] Rahul - Web Development Lead
- [ ] Vigya - Marketing Lead
- [ ] Vishal Sankar- App Development Lead

**Comment by sn10-debug** [comment]
I am ready to work on this issue. Can you please assign me?

**Comment by Arjun31415** [comment]
Please refer the existing template shown in Readme.md

**Comment by Arjun31415** [comment]
this is completed now
