### ISSUE TITLE
feat: Footer

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#23]
Require a professional looking footer

**Comment by sn10-debug** [comment]
I am ready to work on this issue . Can you please assign me ?

**Comment by Arjun31415** [comment]
> I am ready to work on this issue . Can you please assign me ?

Please finish existing assigned issue and then I can assign you another

**Comment by rshirva** [comment]
Hey there @Arjun31415, I would like to work on this. Kindly assign this to me.
