### ISSUE TITLE
feat: Dynamically get Contributors List

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#35]
This is a quite complex feature. Will be first done on dev branch
We can fetch the list of contributors using github api, then parsing it.
Need to check github API docs along with rates so that account is not flagged due to too many requests

**Comment by pythongiant** [comment]
Hey @Arjun31415 , Have a look at https://github.com/mgechev/github-contributors-list and https://www.jsdelivr.com/package/npm/github-contributors-list

Github OAuth token can be used to boost the limit to 5000, but for unauthenticated users the limit is 60 reqs/hour. Given the usual traffic on the website, I dont think the requests are a major issue.

**Comment by Arjun31415** [comment]
Hmm yeah that seems quite reasonable. We can also use the caching of request responses to further optimise it

**Comment by pythongiant** [comment]
yep, might be tricky with vercel though although im not sure its really that necessary given the expected traffic is going to be far less than 5K per hour. lemme know if there is anyway i could help out, seems interesting to work on.

**Comment by Arjun31415** [comment]
> yep, might be tricky with vercel though although im not sure its really that necessary given the expected traffic is going to be far less than 5K per hour. lemme know if there is anyway i could help out, seems interesting to work on.

I can assign the issue to you, if you have a clear idea of how you are going to approach it, else i will have to do it myself

**Comment by pythongiant** [comment]
@Arjun31415 I would love that, but i would love to have a design file to work alongside with it for the UX of the website.

**Comment by Arjun31415** [comment]
Yeah please just try to get the list of contributors, later we can look at the design, Make a a server side endpoint in the `/api` route
in `/pages/api` directory

**Comment by pythongiant** [comment]
@Arjun31415 this issue can be closed now

**Comment by Arjun31415** [comment]
Fixed in #49
