### ISSUE TITLE
Adding Vision Page according to GDSC Website Mockup

### ISSUE THREAD

**Issue by jaydeepdey03** [dscvitc/dscvitchennai#52]
I want to add responsive vision page of the website. Kindly assign me the issue

The following is the screenshot of the mockup

![image](https://user-images.githubusercontent.com/75583927/194852870-8697bb00-cfcb-4277-ae41-f978bba85de8.png)

**Comment by Arjun31415** [comment]
@jaydeepdey03 please check the main branch now, a small part of the vision feature is now complete

**Comment by Arjun31415** [comment]
Please proceed accordingly
