### ISSUE TITLE
Responsive navbar for mobile device

### ISSUE THREAD

**Issue by mr-vijaychauhan** [dscvitc/dscvitchennai#55]
Can you assign me ??? Also which branch you have work. I didn't find current status of this design

**Comment by KaxitPandya** [comment]
@mr-vijaychauhan  @pythongiant  @SreejithNS  @RAvengineer  @abhishekkumkar  I have created many responsive websites using Tailwind CSS, I can make the Navbar Responsive, Please assign it to me

**Comment by EmmanuelAllanMJ** [comment]
Can I work on this issue

**Comment by Arjun31415** [comment]
Fixed in #78
