### ISSUE TITLE
Dynamic Contributors Page Pt 2

### ISSUE THREAD

**Issue by Arjun31415** [dscvitc/dscvitchennai#57]
Generate the contributors page dynamically using the newly created api endpoint at `/api/contributors/`

**Comment by jessej-samuel** [comment]
Hey, can I work on this?

**Comment by Arjun31415** [comment]
Yeah go ahead

**Comment by jessej-samuel** [comment]
Hey, Check the PR above 👆 I am pretty sure everything works. Lmk if any changes are needed!
