### ISSUE TITLE
[FEATURE] Added and Improved Vision Page

### ISSUE THREAD

**Issue by jaydeepdey03** [dscvitc/dscvitchennai#66]
### Description

Suggestion to add a Vision Page to the website

### Expected Behaviour

![image](https://user-images.githubusercontent.com/75583927/196021073-78b1bd32-2af8-48b0-9d3b-f783e6963171.png)

### Current Behaviour

![image](https://user-images.githubusercontent.com/75583927/196021080-e8d3c7be-34bf-4c5c-aeda-903911aab358.png)

**Comment by jaydeepdey03** [comment]
@Arjun31415 @FidalMathew Kindly assign me the issue

**Comment by Arjun31415** [comment]
Done
