### ISSUE TITLE
[FEATURE] Adding Footer Component

### ISSUE THREAD

**Issue by Harikrish-rrk** [dscvitc/dscvitchennai#68]
### Description

I want to add the footer component to the website as per the mockup given

Given:
![image](https://user-images.githubusercontent.com/110128554/196031886-758dcf12-5e5a-4533-9612-1aa0ecd57769.png)

Suggestion:
![image](https://user-images.githubusercontent.com/110128554/196031882-1aff5fee-5c68-4692-82e1-a4161d361a92.png)

Kindly assign me this issue @FidalMathew @arju

**Comment by FidalMathew** [comment]
@Harikrish-rrk assigned you the issue.
