### ISSUE TITLE
[FEATURE] Adding a board member page using SwiperJS

### ISSUE THREAD

**Issue by jaydeepdey03** [dscvitc/dscvitchennai#70]
### Description

@FidalMathew @Arjun31415 
I want to add an scrollable swiper cards featuring board members of GDSC Leads, as per the mockup

I have attached the Screenshot below

![image](https://user-images.githubusercontent.com/75583927/196084134-50bc998d-426f-4083-a96d-e061a86fb8b6.png)

Kindly assign the task to me

### Expected Behaviour

![localhost_3000_ (2)](https://user-images.githubusercontent.com/75583927/196084781-ef84c7cf-308c-4de5-a080-7e98ce7448e0.png)

**Comment by jaydeepdey03** [comment]
The content of card can be dynamically changed via `./data/Boardmember.json`

**Comment by Arjun31415** [comment]
Alright but please use the react version of it from here https://swiperjs.com/react
