### ISSUE TITLE
[FEATURE] ANIMATION ON SCROLL

### ISSUE THREAD

**Issue by mohammadshaad** [dscvitc/dscvitchennai#79]
### Description

I want to add animation on scroll effect on the website

**Comment by Arjun31415** [comment]
Sry for late reply. You can work on this

**Comment by mohammadshaad** [comment]
okay Arjun bhayyya

**Comment by mohammadshaad** [comment]
Assign me this issue please

**Comment by Arjun31415** [comment]
done
