### ISSUE TITLE
broken navbar hyperlinks

### ISSUE THREAD

**Issue by shubhi-tiwari** [dscvitc/dscvitchennai#81]
### Description

- the navbar hyperlinks only lead to the "home page" (not to and fro as i expected) 

https://user-images.githubusercontent.com/94098024/198199578-0bf2c39b-88d6-4656-b0b2-12894fe8e800.mp4

- the logo hyperlink is broken
![image](https://user-images.githubusercontent.com/94098024/198199187-b306a181-bbe3-4253-a80f-8f89125a9f55.png)

- the arrow heads are not responsive

[visited the website on: Chrome, Tor, Brave]
//sincere apologies if these bugs are already being addressed or wips but i couldnt find them personally.

### Expected Behaviour

- expected the navbars to lead to the resp page
- expected the logo hyperlink to lead to official social media handles or such
- expected the arrow heads to lead to the next page

### What happened?

- navbar pages lead only to homepage [not responsive when interacted with on the home page]
- logo hyperlink leads to a broken page
- arrow heads are not responsive

### Version

[link provided in the repo]
http://dscvitchennai-nine.vercel.app/

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhijithGanesh** [comment]
@Arjun31415 I would like to be assigned to this

**Comment by Arjun31415** [comment]
Ok create a PR

**Comment by Arjun31415** [comment]
is this fixed in the latest PR #88 @AbhijithGanesh ?

**Comment by AbhijithGanesh** [comment]
It isn't cuz idk if it's a SPA

**Comment by Arjun31415** [comment]
Ok will you be fixing this ?

**Comment by Aditya-Jyoti** [comment]
@vaibhavTekk @EmmanuelAllanMJ fixed this issue, if you could assign me I would create a PR to make the respective changes

**Comment by Aditya-Jyoti** [comment]
Issue closed after new merge.
