### ISSUE TITLE
NavBar buttons aren't working

### ISSUE THREAD

**Issue by AnshuPathak-88825** [dscvitc/dscvitchennai#82]
### Description

there's no any link avaible in navbar button

### What happened?

A bug happened! when we click button that will take us  to that section

### Version

Don't know version

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhijithGanesh** [comment]
@Arjun31415 I would like to be assigned to this

**Comment by AbhijithGanesh** [comment]
Duplicate of #81
