### ISSUE TITLE
Update pictures of the GDSC leads

### ISSUE THREAD

**Issue by FidalMathew** [dscvitc/dscvitchennai#83]
### Description

![image](https://user-images.githubusercontent.com/84982038/211188629-51b58088-6ccb-48a0-ac28-8fdd4572938f.png)

### What happened?

A bug happened!

### Version

http://dscvitchennai-nine.vercel.app/

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhijithGanesh** [comment]
@FidalMathew This issue can be closed
