### ISSUE TITLE
[FEATURE] Upgrade NextJS version and migrate from pages to app router

### ISSUE THREAD

**Issue by vaibhavTekk** [dscvitc/dscvitchennai#97]
### Description

The Repo is currently using NextJS version 12 and the pages router, Need to upgrade to NextJS Version 13 and migrate from pages router to app router

### Expected Behaviour

- use NextJS Version 13 
- routing using app router

### Current Behaviour

 - Uses NextJS Version 12 
 - Routing done using pages router

### Additional information

Migration Guide:
https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app

**Comment by abhii2003** [comment]
/assign
please assign me to this

**Comment by DylanP97** [comment]
Hi, 
I can do that, let me know if you need my help

**Comment by EmmanuelAllanMJ** [comment]
[`PR`](https://github.com/dscvitc/dscvitchennai/pull/117) resolves this issue
