### ISSUE TITLE
[FEATURE] Update Board members

### ISSUE THREAD

**Issue by EmmanuelAllanMJ** [dscvitc/dscvitchennai#98]
### Description

The current Board members on the website are not up to date. I would like to open an issue to update the Board members on the website to reflect the current Board members.

### Additional information

Members List
1) Aditi Jha - Overall Lead
2) Subham Ghosh - Outreach Lead
3) Syed Omar Albeez- Management Lead
4) Janhavi Chaurasia - Management Lead
5) Emmanuel Allan M J - Web dev Lead
6) Sparsh Chakraborty - Social Media Lead
7) Jeevan Alexen Kavalam - Competitive Programming Lead
8) Vaibhav T S - Web Dev Lead
9) Swastika Shukla - Blockchain Lead 
10) Ameiy Acharya - Blockchain Lead
11) Amara J - Social Media Lead
12) Jaskaran Singh Walia - Data Science Lead
13) Achintya Singh - Competitive Programming Lead
14) Zahran Sajid - Open Source Lead
15) Anurag Tamhankar - Design Lead
16) Mihika Dhakray - UI/UX Lead
17) Naveen Shankar Choudhury - Marketing Lead
18) Cynthia Konar - App Dev Lead

**Comment by Aditya-Jyoti** [comment]
Is there any list of current board members?

**Comment by EmmanuelAllanMJ** [comment]
List has been updated

**Comment by Aditya-Jyoti** [comment]
Ok thank you, i would like to work on this issue

**Comment by Aditya-Jyoti** [comment]
these for data values
```
    description: "",
    github: "",
    linkedIn: "",
    color: "#4b916c",
```
dont currently do anything, is there any plans on implementing them

**Comment by Aditya-Jyoti** [comment]
for reference
 
- [ ] Aditi Jha - Overall Lead
- [ ] Subham Ghosh - Outreach Lead
- [x] Syed Omar Albeez- Management Lead
- [ ] Janhavi Chaurasia - Management Lead
- [ ] Emmanuel Allan M J - Web dev Lead
- [x] Sparsh Chakraborty - Social Media Lead
- [x] Jeevan Alexen Kavalam - Competitive Programming Lead
- [ ] Vaibhav T S - Web Dev Lead
- [ ] Swastika Shukla - Blockchain Lead
- [ ] Ameiy Acharya - Blockchain Lead
- [x] Amara J - Social Media Lead
- [x] Jaskaran Singh Walia - Data Science Lead
- [x] Achintya Singh - Competitive Programming Lead
- [x] Zahran Sajid - Open Source Lead
- [ ] Anurag Tamhankar - Design Lead
- [ ] Mihika Dhakray - UI/UX Lead
- [ ] Naveen Shankar Choudhury - Marketing Lead
- [ ] Cynthia Konar - App Dev Lead

**Comment by vaibhavTekk** [comment]
can you make sure you dont delete the data of the previous term ?, just create a folder called prev-years and store the older files in there, just for the sake of archival..

**Comment by Aditya-Jyoti** [comment]
Would you like me to retain the MemberList.js file as well along with the images? Or just the images

**Comment by vaibhavTekk** [comment]
the MemberList.js file as well, just rename the file and add a comment inside saying "GDSC 2022-2023 Term"

**Comment by Aditya-Jyoti** [comment]
> the MemberList.js file as well, just rename the file and add a comment inside saying "GDSC 2022-2023 Term"

Ok understood, will do so
